### ISSUE TITLE
Auto-scroll carousel on Home Page

### ISSUE THREAD

**Issue by utkarshluthra** [cu-coders/cucoders#39]
**Is your feature request related to a problem? Please describe.**
The Carousel on the home page is static and needs to be moved to update.

**Describe the solution you'd like**
Auto-scroll carousel on a scroll or on time

**Describe alternatives you've considered**
Use a move visible next button next to the carousel

**Additional context**
![image](https://user-images.githubusercontent.com/64695632/137421004-d8fa333a-c9b0-41c6-9cd1-27ceb0ac581e.png)

**Comment by ank1traj** [comment]
Solved with commit[ 08ae344d5ccc6f7cf224d922035cc1e825b88e77](https://github.com/cu-coders/cucoders/commit/08ae344d5ccc6f7cf224d922035cc1e825b88e77)
