### ISSUE TITLE
Issue with Events page frontend

### ISSUE THREAD

**Issue by utkarshluthra** [cu-coders/cucoders#40]
**Describe the bug**
1. Font color of the page is not correct
2. Overlapping divs

**To Reproduce**
1. Go to https:main.cuchapter.tech
2. Click on Events
4. See error on Events Page

**Expected behavior**
1. Color should be same as site theme
2. proper padding on div

**Screenshots**
![image](https://user-images.githubusercontent.com/64695632/137421662-c66684a2-d068-42be-bad1-e060216e274c.png)
![image](https://user-images.githubusercontent.com/64695632/137421692-c5fda4a8-9c2a-4c57-a2ed-eba3e8918b1e.png)

**Desktop (please complete the following information):**
 - OS: Windows/Linux
 - Browser Chrome
 - Version 92

**Smartphone (please complete the following information):**
 - Device: Samsung A10s
 - OS: Android 11
 - Browser Chrome
 - Version 93

**Comment by aditi944** [comment]
Can I work on this issue?

**Comment by ank1traj** [comment]
> Can I work on this issue?

Most issues are fixed but you can check it once.

**Comment by aditi944** [comment]
> > Can I work on this issue?
> 
> Most issues are fixed but you can check it once.

okay sure

**Comment by Karan-Dhingra** [comment]
I think now you can close this issue, as it is already resolved

**Comment by ank1traj** [comment]
This issue has been fixed.
