### ISSUE TITLE
Website Title Wrapping

### ISSUE THREAD

**Issue by utkarshluthra** [cu-coders/cucoders#43]
**Describe the bug**
The title of the website, `CU-Coders`, is wrapping into two lines at 100% zoom.

**To Reproduce**
1. Go to https://main.cuchapter.tech
3. See error on the top left

**Expected behavior**
Title of Website should not wrap

**Screenshots**
![image](https://user-images.githubusercontent.com/64695632/137422989-cdbdbe7d-8895-4c75-989b-4c0acdc2c658.png)
**Desktop (please complete the following information):**
 - OS: Windows/Linux
 - Browser Chrome
 - Version 93

**Comment by Karan-Dhingra** [comment]
I have fixed this bug 
please review #82
